services:
  traefik:
    image: traefik:v3.0
    command:
      - --providers.http.endpoint=http://configserver:80/traefik_config.json
      - --entryPoints.web.address=:80
      - --api.insecure=true
    ports:
      - "8081:80"       # Incoming HTTP traffic
      - "8080:8080"   # For Traefik dashboard (if needed)
    depends_on:
      - configserver
    networks:
      - traefik-net

  configserver:
    image: nginx:alpine
    volumes:
      - ./config:/usr/share/nginx/html:ro
    # No ports mapping is needed because Traefik will use the internal Docker network to access this service.
    networks:
      - traefik-net


  service1:
    image: nginx:alpine
    volumes:
      - ./services/1:/usr/share/nginx/html:ro
    networks:
      - traefik-net

  service2:
    image: nginx:alpine
    volumes:
      - ./services/2:/usr/share/nginx/html:ro
    networks:
      - traefik-net

  service3:
    image: nginx:alpine
    volumes:
      - ./services/3:/usr/share/nginx/html:ro
    networks:
      - traefik-net

  service4:
    image: nginx:alpine
    volumes:
      - ./services/4:/usr/share/nginx/html:ro
    networks:
      - traefik-net

networks:
  traefik-net: